apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3  # Number of pods you want to run
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image:  myflask:app  # Replace with your Docker image name and tag
          ports:
            - containerPort: 5000  # Port your Flask app is running on
