apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 5000  # Port to expose on the LoadBalancer
      targetPort: 5000  # Port your Flask app is listening on in the pods
  type: LoadBalancer  # Service type as LoadBalancer
